CREATE TABLE IF NOT EXISTS auth_oauth_client (
    id varchar(64) NOT NULL PRIMARY KEY,
    client_id varchar(128) NOT NULL COMMENT 'OAuth client_id',
    client_secret varchar(255) DEFAULT NULL COMMENT 'OAuth client_secret，建议保存BCrypt哈希，公开客户端为空',
    name varchar(255) DEFAULT NULL COMMENT '客户端名称',
    client_type varchar(32) NOT NULL DEFAULT 'confidential' COMMENT '客户端类型：public/confidential',
    token_endpoint_auth_method varchar(64) NOT NULL DEFAULT 'client_secret_basic' COMMENT 'token endpoint认证方式',
    grant_types varchar(255) NOT NULL DEFAULT 'client_credentials' COMMENT '允许的grant type，空格或逗号分隔',
    redirect_uris varchar(2048) NOT NULL DEFAULT '' COMMENT '允许的redirect_uri，换行或空格分隔',
    scopes varchar(512) NOT NULL COMMENT '允许的scope，空格或逗号分隔',
    audiences varchar(512) NOT NULL COMMENT '允许的audience/resource，空格或逗号分隔',
    client_uri varchar(512) DEFAULT NULL COMMENT '客户端主页',
    logo_uri varchar(512) DEFAULT NULL COMMENT '客户端图标',
    access_token_ttl_seconds int NOT NULL DEFAULT 900 COMMENT 'access token有效秒数',
    code varchar(255) DEFAULT NULL COMMENT '编码',
    description varchar(255) DEFAULT NULL COMMENT '说明',
    create_date_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    create_name varchar(255) DEFAULT NULL COMMENT '创建人',
    modify_date_time datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    modify_name varchar(255) DEFAULT NULL COMMENT '修改人',
    is_delete bit(1) DEFAULT b'0' COMMENT '删除状态',
    type int DEFAULT '0' COMMENT '类型（0：默认）',
    state int DEFAULT '1' COMMENT '状态（1：启用，2：禁用）',
    label varchar(255) DEFAULT NULL COMMENT '标签',
    sorting int DEFAULT '0' COMMENT '排序',
    version int DEFAULT '1' COMMENT '版本号',
    tenant_id varchar(64) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '1' COMMENT '租户id',
    UNIQUE KEY uk_auth_oauth_client_client_id (client_id),
    KEY idx_auth_oauth_client_state (state),
    KEY idx_auth_oauth_client_tenant_id (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='OAuth客户端表';

INSERT IGNORE INTO auth_oauth_client
(id, client_id, client_secret, name, client_type, token_endpoint_auth_method, grant_types, redirect_uris, scopes, audiences, client_uri, logo_uri, access_token_ttl_seconds,
 code, description, create_name, modify_name, tenant_id, state, version)
VALUES
('oauth_client_mcp_local_dev',
 'mcp-local-dev',
 '$2a$10$G6.TNOPHyywmKWxrCSDoxOD/kEQbmLPs1yVsBgO3uq1.oyE0ShWzC',
 '本地 MCP client_credentials',
 'confidential',
 'client_secret_basic',
 'client_credentials',
 '',
 'mcp.tools.read mcp.tools.call',
 'http://localhost:7100/api/mcp',
 'http://localhost:7100',
 NULL,
 2592000,
 'mcp-local-dev',
 '本地 Cherry Studio/语聚联调 MCP Streamable HTTP 的保密客户端。client_secret 明文仅通过安全渠道交付。',
 'system',
 'system',
 '100',
 1,
 1),
('oauth_client_yuju_mcp_prod',
 'yuju-mcp-prod',
 NULL,
 '语聚正式 MCP OAuth',
 'confidential',
 'client_secret_basic',
 'client_credentials',
 '',
 'mcp.tools.read mcp.tools.call',
 'https://report-api.meilianshuke.com/api/mcp',
 'https://report-api.meilianshuke.com',
 NULL,
 2592000,
 'yuju-mcp-prod',
 '正式环境语聚智能体调用 MCP Streamable HTTP 的保密客户端。上线前请在管理端录入 client_secret 并启用。',
 'system',
 'system',
 '100',
 2,
 1);
