CREATE TABLE IF NOT EXISTS auth_external_client (
    id varchar(64) NOT NULL PRIMARY KEY,
    provider_code varchar(64) NOT NULL COMMENT '外部系统编码',
    client_id varchar(128) NOT NULL COMMENT '三方客户端ID',
    client_secret varchar(255) NOT NULL COMMENT '三方客户端密钥',
    name varchar(255) DEFAULT NULL COMMENT '客户端名称',
    signature_required bit(1) DEFAULT b'1' COMMENT '是否要求签名',
    allowed_clock_skew_seconds int DEFAULT '300' COMMENT '允许的签名时钟偏差秒数',
    code varchar(255) DEFAULT NULL COMMENT '编码',
    description varchar(255) DEFAULT NULL COMMENT '说明',
    create_date_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    create_name varchar(255) DEFAULT NULL COMMENT '创建人',
    modify_date_time datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    modify_name varchar(255) DEFAULT NULL COMMENT '修改人',
    is_delete bit(1) DEFAULT b'0' COMMENT '删除状态',
    type int DEFAULT '0' COMMENT '类型（0：默认）',
    state int DEFAULT '1' COMMENT '状态（1：启用，2：禁用）',
    label varchar(255) DEFAULT NULL COMMENT '标签',
    sorting int DEFAULT '0' COMMENT '排序',
    version int DEFAULT '1' COMMENT '版本号',
    tenant_id varchar(64) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '1' COMMENT '租户id',
    UNIQUE KEY uk_auth_external_client_provider_client (provider_code, client_id),
    KEY idx_auth_external_client_state (state)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='三方认证客户端表';

CREATE TABLE IF NOT EXISTS auth_external_identity (
    id varchar(64) NOT NULL PRIMARY KEY,
    provider_code varchar(64) NOT NULL COMMENT '外部系统编码',
    external_tenant_id varchar(128) NOT NULL DEFAULT '' COMMENT '外部租户ID',
    external_user_id varchar(128) NOT NULL DEFAULT '' COMMENT '外部用户ID',
    external_patient_id varchar(128) NOT NULL DEFAULT '' COMMENT '外部患者或业务主体ID',
    local_tenant_id varchar(64) NOT NULL COMMENT '本地租户ID',
    local_user_id varchar(64) NOT NULL COMMENT '本地用户ID',
    subject_type varchar(32) DEFAULT NULL COMMENT '主体类型：USER/PATIENT/DOCTOR',
    display_name varchar(255) DEFAULT NULL COMMENT '展示名称',
    metadata_json json DEFAULT NULL COMMENT '三方扩展元数据JSON',
    code varchar(255) DEFAULT NULL COMMENT '编码',
    description varchar(255) DEFAULT NULL COMMENT '说明',
    create_date_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    create_name varchar(255) DEFAULT NULL COMMENT '创建人',
    modify_date_time datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    modify_name varchar(255) DEFAULT NULL COMMENT '修改人',
    is_delete bit(1) DEFAULT b'0' COMMENT '删除状态',
    type int DEFAULT '0' COMMENT '类型（0：默认）',
    state int DEFAULT '1' COMMENT '状态（1：启用，2：禁用）',
    label varchar(255) DEFAULT NULL COMMENT '标签',
    sorting int DEFAULT '0' COMMENT '排序',
    version int DEFAULT '1' COMMENT '版本号',
    tenant_id varchar(64) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '1' COMMENT '租户id',
    UNIQUE KEY uk_auth_external_identity_subject (provider_code, external_tenant_id, external_user_id, external_patient_id),
    KEY idx_auth_external_identity_local_user (local_tenant_id, local_user_id),
    KEY idx_auth_external_identity_state (state)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='外部身份映射表';

CREATE TABLE IF NOT EXISTS auth_external_signature_nonce (
    id varchar(64) NOT NULL PRIMARY KEY,
    provider_code varchar(64) NOT NULL COMMENT '外部系统编码',
    client_id varchar(128) NOT NULL COMMENT '三方客户端ID',
    nonce varchar(128) NOT NULL COMMENT '随机串',
    timestamp_millis bigint NOT NULL COMMENT '请求时间戳毫秒',
    expire_date_time datetime DEFAULT NULL COMMENT '过期时间',
    code varchar(255) DEFAULT NULL COMMENT '编码',
    description varchar(255) DEFAULT NULL COMMENT '说明',
    create_date_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    create_name varchar(255) DEFAULT NULL COMMENT '创建人',
    modify_date_time datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    modify_name varchar(255) DEFAULT NULL COMMENT '修改人',
    is_delete bit(1) DEFAULT b'0' COMMENT '删除状态',
    type int DEFAULT '0' COMMENT '类型（0：默认）',
    state int DEFAULT '1' COMMENT '状态（1：启用，2：禁用）',
    label varchar(255) DEFAULT NULL COMMENT '标签',
    sorting int DEFAULT '0' COMMENT '排序',
    version int DEFAULT '1' COMMENT '版本号',
    tenant_id varchar(64) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '1' COMMENT '租户id',
    UNIQUE KEY uk_auth_external_signature_nonce (provider_code, client_id, nonce),
    KEY idx_auth_external_signature_nonce_expire (expire_date_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='三方开放接口签名 nonce 表';
