server:
  port: 7500
spring:
  main:
    allow-bean-definition-overriding: true
security:
  auth:
    permit-urls:
      - /actuator/**
      - /doc.html
      - /webjars/**
      - /swagger-ui/**
      - /v3/api-docs/**
      - /auth/tenants
      - /auth/login
